syntax on
set cindent
set nowrap
set autoindent
set smartindent
set ruler
set number
set sm
set tabstop=4
set shiftwidth=4
set softtabstop=4
set splitbelow
set splitright
set foldmethod=indent
set foldlevel=99
set title
set cursorline
set nobackup
set incsearch
set hlsearch
set encoding=utf8
set nocompatible
set clipboard=unnamed
set showmatch
set showcmd 
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
"Bundle 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'
Plugin 'https://github.com/nvie/vim-flake8'
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'AutoComplPop'
Plugin 'taglist-plus'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'scrooloose/nerdcommenter'
Plugin 'mattn/emmet-vim'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'taglist.vim'
Plugin 'L9'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" Add all your plugins here (note older versions of Vundle used Bundleinstead of Plugin)
" All of your Plugins must be added before the following line
call vundle#end()            " required

let NERDTreeWinPos = "left"
let NERDTreeChDirMode=1
let NERDTreeShowHidden=1
let NERDTreeKeepTreeInNewTab=1
let NERDTreeQuitOnOpen=0
let g:nerdtree_tabs_open_on_gui_startup=0
let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_Inc_Winwidth = 0
let Tlist_Exit_OnlyWindow = 0
let Tlist_Auto_Open = 0
let Tlist_Use_Right_Window = 1
let mapleader=","
nmap <F6> :NERDTree<CR>
nmap <F8> :TlistToggle<CR>
nmap <C-f> :NERDTreeFind<CR>
nmap <Leader>n :NERDTreeToggle<CR>
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
autocmd FileType python map <buffer> <F3> :call Flake8()<CR>
autocmd VimEnter * NERDTree
let g:flake8_show_in_file=1
let g:flake8_max_markers=500 
filetype plugin indent on 

" Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
